select* from customer limit 20;

--total revenue generated by male vs female cstmr
select gender,sum(purchase_amount) as revenue
from customer
group by gender

--which customers used a discount but still spent more than the average purchase amount
select  customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--top 5 prdcts with highest average review rating
select item_purchased,round(avg(review_rating::numeric),2) as "average_prdct_rating"
from customer
group by item_purchased
order by average_prdct_rating desc
limit 5;

--compare the average purchase amounts b/w standard and express shipping
select round(avg(purchase_amount),2),shipping_type
from customer
where shipping_type in('Standard','Express')
group by shipping_type

--do subscribed customers spend more? compare average spend and total revenue b/w subscribers and non-sub
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--5 products having the highest % of purchases with discounts applied?
select item_purchased,
round(avg(case when discount_applied='Yes' then 1 else 0 end )* 100,2)  as discout_rate
from customer 
group by item_purchased
order by discout_rate desc
limit 5;

--segment customers into new,returning and loyal based on their total number of prvs
--purchases and show the count of each segment
with customer_type as(
select customer_id,previous_purchases,
case 
    when previous_purchases=1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
from customer
)
select customer_segment,count(*) as "no.of customers"
from customer_type
group by customer_segment;

--what are the top 3 purchased products within each category
with item_counts as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)  desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

--are customers who are repeat buyers (more than 5 prvs purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

--what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc ;


	












